### ISSUE TITLE
generate Bills for IRT as well

### ISSUE THREAD

**Issue by JasonBuckner** [soberstadt/bill-bucks-generator#16]
As mentioned [here](https://github.com/soberstadt/bill-bucks-generator/issues/6#issuecomment-726139948), some folks from International Recording Team with Jesus Film Project have requested the ability to use the Bill Bucks generator to generate 1 and 5 denomination Bills using different images. I've emailed those images to Spencer & Shelby.

**Comment by soberstadt** [comment]
I'm thinking we can add a route of https://bill-buck-generator.herokuapp.com/jfp which would redirect to https://bill-buck-generator.herokuapp.com/bucks/new?dept=jfp that would show the alternitive images. Files:
![1_Digital_Bill_Buck_for_IRT](https://user-images.githubusercontent.com/1080613/100674368-05e25600-3333-11eb-9da8-1948f9df9b83.png)
![5_Digital_Bill_Bucks_for_IRT](https://user-images.githubusercontent.com/1080613/100674377-07ac1980-3333-11eb-81b6-5aa85f7b5a3b.png)

**Comment by soberstadt** [comment]
@dbenton9 if you find yourself twiddling your thumbs, feel free to pick this up. But let me know if you do so I don't also start working on it :D We can also pair on this sometime if you want.

**Comment by JasonBuckner** [comment]
Thanks for uploading the files; I couldn't figure out how to do that (and _now_ I notice the clear instructions right below this very textbox here in the UI).
Just wondering... why use `jfp` and not `irt` in that URL? There may be other teams within JPF that will someday want Bill Bucks too.

**Comment by dbenton9** [comment]
@soberstadt just shot you a calendar invite to pair on this!

**Comment by dbenton9** [comment]
@JasonBuckner Check it out! [IRT Bill Bucks](https://bill-buck-generator.herokuapp.com/?dept=irt)

I've got a tweak some javascript later but this is live and ready for use.

**Comment by soberstadt** [comment]
for future reference, initial support for this was added with c92da0ac14ae4dcfa70a08b68f58401723c22e5b

**Comment by JasonBuckner** [comment]
Excellent! Can you rename 'Roman' to 'Captain'? I think that's the name they typically use.
And they may want 'Magdalena' instead of 'Mary' too. I'll ask, and cc you both.
