### ISSUE TITLE
Can you give ability to change the $ amount.

### ISSUE THREAD

**Issue by garivaldo** [soberstadt/bill-bucks-generator#17]
If I wanted to give $2 or $3 to the same person, how can I do that once.

**Comment by JasonBuckner** [comment]
I do this _frequently_ and would love a way to generate multiple Bills at once. 
My current workaround is to append the text "1/8", "2/8", "3/8", "5/8", etc within the Note section of each Bill... but that's kind of a pain.

**Comment by soberstadt** [comment]
Yes, I also agree with this but I don't see an obvious solution with how this currently works. I have started some work on supporting sending the bills for you via email (#14) and after that is added it would me much easier to have the email include multiple bills with the "1/3" added to it.

**Comment by soberstadt** [comment]
@garivaldo We're working to write a communication to the department, but for now, feel free to generate any number of bills with the new "count" field! Give us any feedback on the new features you have!
