### ISSUE TITLE
blank lines & CRLF's are (often) stripped out

### ISSUE THREAD

**Issue by JasonBuckner** [soberstadt/bill-bucks-generator#18]
I've had this happen a few times and each time I go back to capture a screenshot to make a bug report, I can't duplicate duplicate the problem. But I caught it this time! Ah ha!

Here's what I submitted (using FF 83.0). Note the line breaks.
![CaptureA](https://user-images.githubusercontent.com/19961846/102269517-bed79180-3eea-11eb-9686-d340d0b235a5.jpg)

Here is the Bill that was generated. Note my generosity. Kidding. Note Robin's helpfulness. 
![CaptureB](https://user-images.githubusercontent.com/19961846/102269845-34dbf880-3eeb-11eb-9ae9-b79fff800904.JPG)

In case it helps, [here's the URL](https://bill-buck-generator.herokuapp.com/bucks/new?buck_type=vonette&dept=&for_message=Thanks+for+teaching+me+how+to+look+up+addresses+in+connectandcare.cru.org%21+%0D%0AI+was+able+to+copypaste+them+right+into+MPDX%2C+export+my+Christmas+Card+list+and+BINGO%21+Done.+%0D%0AEasy-peasy.&from=Jason+Buckner&to=Robin+Kirchhof) for the generated Bill. It seems to behave the same way in Brave 1.18.70 & with a clean cache.

**Comment by soberstadt** [comment]
Not sure if I should label this as a bug or a feature request.

**Comment by JasonBuckner** [comment]
FWIW, blank lines get stripped out as well.
![CaptureC](https://user-images.githubusercontent.com/19961846/102273426-4d9add00-3ef0-11eb-9efc-c3d2abf81259.JPG)


Input doesn't match output. 
Seems like a bug.

**Comment by dbenton9** [comment]
@JasonBuckner Done. Easy-peasy.
