### ISSUE TITLE
Where's Vonette?

### ISSUE THREAD

**Issue by andreabitney** [soberstadt/bill-bucks-generator#28]
Looks like the option to select a Vonette has disappeared. Sure you could send 5 Bills, but there's something so exciting about seeing a bright pink Vonette come your way :)

**Comment by soberstadt** [comment]
I can confirm, my experience is that those Vonies give me a euphoric feeling! The bill buck generator will try its best to satisfy that craving when you input a number greater than 4. 3 will not produce a Vonette. 2 is no enough for the grail you seek. 1 is hardly any bills at all, but I still send them out. 😁

https://bill-buck-generator.herokuapp.com/bucks/new?count=17&for_message=Being+great+at+wasting+time%21+🕺🐙&from=&to=Spencer+Oberstadt

**Comment by andreabitney** [comment]
Oh look at that! Nifty :D Sorry I missed that, thanks for letting me know!
