### ISSUE TITLE
set 'reply-to' on emailed Bills be to the sender's email address

### ISSUE THREAD

**Issue by JasonBuckner** [soberstadt/bill-bucks-generator#29]
When a Bill is emailed, an Okta login is required. It would be nice to set the "Reply-To" value in that system-generated email to match the Bill Buck sender's email address (as pulled from Okta).

Ideally, you'd pull the `email` Okta Profile attribute, but the `login` value would work too if the former attribute is not exposed. 
Note that the Okta login ID is not _always_ a valid email address and it _doesn't have to be_ the user's _current_ email address, but they almost always match (like, 99.9% of the time).

**Comment by soberstadt** [comment]
@JasonBuckner so can this be closed now?

**Comment by soberstadt** [comment]
This was one of those "it helps if you actually send the information" situations: https://github.com/soberstadt/bill-bucks-generator/commit/c0940593f081070c993457814c2c8ae1e950fb34#diff-8c149e9411dae9e45615d926deae17d661178f2b98197ef50265b5c2c9e208d5L54-R58

**Comment by JasonBuckner** [comment]
Thanks to this feature, I just received a "Thanks" for sending a thanks. Thanks for adding it!
