### ISSUE TITLE
Support Emoji in "For:"

### ISSUE THREAD

**Issue by soberstadt** [soberstadt/bill-bucks-generator#3]
This is trickier than I expected. It seems like the best option for this is using the pango text coder:
http://www.imagemagick.org/Usage/text/#pango

But, I have struggled with two problems:
- getting imagemagick installed locally with pango
- figuring out how to have rmagick use pango when we call `annotate`

**Comment by soberstadt** [comment]
Here's the example of using pango with rmagick: https://github.com/rmagick/rmagick/blob/master/examples/pango.rb

**Comment by soberstadt** [comment]
Also, it's helpful to point out that heroku hosts seem to support pango so we might be able to do this only testing in "production".

**Comment by soberstadt** [comment]
I tried a bunch, and I couldn't get imagemagick to render emoji's other than basic ones.
I ssh'ed into the heroku instance (`heroku ps:exec`),
downloaded an emoji font (https://github.com/googlefonts/noto-emoji/blob/master/fonts/NotoColorEmoji.ttf)
and tried using it in the `convert` call:
`convert -font /app/emoji.ttf pango:"Hello! <span font=\"/app/emoji\">🤓</span>How are you?" example.png`

But it still gave me weird square things. So I have given up on this, I have been defeated.

**Comment by dbenton9** [comment]
@soberstadt and I agree this is not worth the effort.
