### ISSUE TITLE
edit subject line in generated emails

### ISSUE THREAD

**Issue by JasonBuckner** [soberstadt/bill-bucks-generator#32]
Current:
You've got Bills (Bucks) from {{sender}}

Suggestion:
Bill Bucks have arrived from {{sender}}

**Comment by soberstadt** [comment]
I was trying to evoke a "You've got mail" nostalgia, but maybe that isn't as widely appreciated, or the novelty wears off quickly.

**Comment by soberstadt** [comment]
(somehow accidentally closed the issue)

@dbenton9 any input on the subject line? 
is this the wrong place for adding delight?
What about we add some emoji?: `Bill Bucks have arrived from {{sender}} 🅱️💌`

**Comment by JasonBuckner** [comment]
I was working under the assumption that {{sender}} needed to be appended to the end since we'd not know the length, etc. 
If that's _not_ the case (and we want to try emoji), let's go with:

`Enclosed: Bill Bucks from {{sender}}! 🅱️💌`
