### ISSUE TITLE
Problem sending bill bucks

### ISSUE THREAD

**Issue by mattdrees** [soberstadt/bill-bucks-generator#33]
I just tried to send some bill bucks by email to a three different folks, and got a generic error each time:

```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
```

**Comment by JasonBuckner** [comment]
@mattdrees I'm unable to duplicate duplicate this issue. Can you retry? Feel free to send a Bill or three my way to test.  ;-)

**Comment by mattdrees** [comment]
turns out my attempt yesterday actually sent a bill buck email to one of the people. So the error was sometime after that email was sent.

Also.
I just tried to send a buck to Jason, and it went through fine.
So whatever caused those error messages yesterday is not causing them today.

**Comment by JasonBuckner** [comment]
Yep. Bill Buck received. Hooray!
And with the new Subject line (#32) too. Nice!

**Comment by soberstadt** [comment]
Unfortunately my logs don't go back very far because of running on a free heroic dyno. If you experience this again, please let me know or reopen this.
